apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: workload-vsphere-tkg1
  namespace: demo1
spec:
  distribution:
    version: v1.17.7
  topology:
    controlPlane:
      count: 1                                 #3 control plane nodes
      class: best-effort-small                  #large size VM
      storageClass: pacific-gold-storage-policy  #Specific storage class for control plane
    workers:
      count: 3                                 #5 worker nodes
      class: best-effort-large               #extra large size VM
      storageClass: pacific-gold-storage-policy   #Specific storage class for workers
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/24"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/22"]           #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["pacific-gold-storage-policy"]
      defaultClass: pacific-gold-storage-policy
