apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: workload-vsphere-tkg1
  namespace: demo1
spec:
  distribution:
    version: v1.17.7    #The full image name is specified
  topology:
    controlPlane:
      count: 1                                 #3 control plane nodes
      class: best-effort-small                  #large size VM
      storageClass: nav-gold-policy  #Specific storage class for control plane
    workers:
      count: 2                #5 worker nodes
      class: best-effort-medium               #extra large size VM
      storageClass: nav-gold-policy   #Specific storage class for workers
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["198.51.100.0/24"]        #Cannot overlap with Supervisor Cluster
      pods:
        cidrBlocks: ["192.0.2.0/22"]           #Cannot overlap with Supervisor Cluster
    storage:
      classes: ["nav-gold-policy"]
      defaultClass: nav-gold-policy
